v7.11.2-IJ2023.2
PlantUML Integration 7.11.1-IJ2023.2 is binary incompatible with IntelliJ IDEA Ultimate IU-232.10335.12 due to the following problem
Method not found (1 problem)
Invocation of unresolved method StaxFactory.createXmlStreamReader$default(...) (1 problem)
Method MySvgDocumentFactoryKt.createSvgDocument(...) contains an invokestatic instruction referencing an unresolved method StaxFactory.createXmlStreamReader$default(...). This can lead to NoSuchMethodError exception at runtime.