java.lang.NullPointerException: Parameter specified as non-null is null: method com.intellij.openapi.wm.impl.WindowManagerImpl.getStatusBar, parameter project 	at com.intellij.openapi.wm.impl.WindowManagerImpl.getStatusBar(WindowManagerImpl.kt) 	at com.intellij.openapi.wm.impl.WindowManagerImpl.getStatusBar(WindowManagerImpl.kt:59) 	at org.plantuml.idea.action.context.CopyDiagramToClipboardContextAction.actionPerformed(CopyDiagramToClipboardContextAction.java:66)